enum NotificationType {
  NOTIFICATION = 'NOTIFICATION',
  ATTEMPT_LOGIN_NOTIFICATION_HIGH_PRIORITY = 'ATTEMPT_LOGIN_NOTIFICATION_HIGH_PRIORITY',
  CHALLENGE = 'CHALLENGE',
  RATE_LIMIT_CHALLENGE = 'RATE_LIMIT_CHALLENGE',
}

export default NotificationType
